spring:
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  application:
    name: todo-server

  datasource:
    url: jdbc:h2:mem:development;Mode=MYSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console
